### ISSUE TITLE
.setup files improvements

### ISSUE THREAD

**Issue by fjouault** [viatra/viatra-cps-benchmark#1]
Hello,

Although I managed to install the benchmark now that it is split over two repositories, I noticed the following inconveniences:
- Viatra CPS git repository URL is not pre-filled, and one has to discover that the following works: https://git.eclipse.org/r/viatra/org.eclipse.viatra.examples
- It would be simpler for non-committers to install the benchmark if the viatra-cps-benchmark & mondo-sam repository URLs were "read-only anonymous" by default.

Thanks,

Frédéric

**Comment by abelhegedus** [comment]
Thanks for the input! I agree that both points should be improved, I will take a look at the setup soon.

**Comment by abelhegedus** [comment]
I have checked the setup:
- all Git Clone tasks are set up in a way that the user has a drop-down list to choose from
- the label of each choice is quite descriptive and the user should be able to select the proper one

I have updated the install guide on the main page to help users in selecting the correct values for these variables.
