### ISSUE TITLE
Add peak memory usage metric

### ISSUE THREAD

**Issue by abelhegedus** [viatra/viatra-cps-benchmark#6]
To better represent the memory usage of the measured tools, we should check the peak usage after the execution of the M2M transformation.

See https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryPoolMXBean.html#getPeakUsage()

**Comment by istvanrath** [comment]
average usage would be useful also

**Comment by abelhegedus** [comment]
> average usage would be useful also

How do you define "average usage"?

Also, we could use http://metrics.dropwizard.io/3.1.0/manual/jvm/ for some more memory metrics (see http://jansipke.nl/getting-metrics-from-the-java-virtual-machine-jvm/ for usage). Note that this does not support neither peak, nor average, but it wraps MemoryMXBeans nicely.

**Comment by istvanrath** [comment]
measure current usage every 10 secs on a background thread. go a gc sweep before and after.

**Comment by abelhegedus** [comment]
> measure current usage every 10 secs on a background thread. go a gc sweep before and after.

This measurement would have to be done independently of the time measurement, since the manual gc would affect that. So we would run a full benchmark with only time measurement and a full with memory measurement, and evaluate the results separately.

**Comment by istvanrath** [comment]
no, I suggest to make 2 gc sweeps, not n+2. this shouldn't be a too big overhead, especially in a multicore environment.

**Comment by abelhegedus** [comment]
Okay, that sounds reasonable.

Is the following workflow what you suggest?
1. GC
2. start background thread (sample total-free memory every 10 sec)
3. start timer
4. do stuff 
5. stop timer
6. stop background thread
7. GC
8. measure persistent memory usage
9. compute average from info gathered by background thread

**Comment by istvanrath** [comment]
yes!

**Comment by abelhegedus** [comment]
https://build.incquerylabs.com/jenkins/job/viatra-cps-benchmark/59/artifact/benchmark/cpsBenchmarkReport.html
